# Anchor.toml - Configuration Reference
#
# This file configures the Anchor workspace for the counter program.
# Key concepts for presenters:
#
# 1. [programs.*] sections map cluster names to Program IDs
# 2. The Program ID must match declare_id! in lib.rs
# 3. [provider] sets default cluster and wallet
# 4. [scripts] defines test commands
#
# Why separate clusters? Different environments (local vs devnet vs mainnet)
# Why same Program ID? Consistency across environments
# 📖 https://www.anchor-lang.com/docs

[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
counter = "FoKCfkWjCJxuHLxHGkzdQ3VXrFgrnGdq4xNsZLnjJLbK"

[programs.devnet]
counter = "FoKCfkWjCJxuHLxHGkzdQ3VXrFgrnGdq4xNsZLnjJLbK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
